"""Added player role tables

Revision ID: 4a5e33eed078
Revises: 
Create Date: 2025-03-19 12:13:23.381990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5e33eed078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allrounders',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('batting_avg', sa.Float(), nullable=False),
    sa.Column('strike_rate', sa.Float(), nullable=False),
    sa.Column('total_wickets', sa.Integer(), nullable=False),
    sa.Column('bowling_avg', sa.Float(), nullable=False),
    sa.Column('best_figures', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('batsmen',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('batting_avg', sa.Float(), nullable=False),
    sa.Column('strike_rate', sa.Float(), nullable=False),
    sa.Column('centuries', sa.Integer(), nullable=False),
    sa.Column('half_centuries', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('bowlers',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('total_wickets', sa.Integer(), nullable=False),
    sa.Column('bowling_avg', sa.Float(), nullable=False),
    sa.Column('economy', sa.Float(), nullable=False),
    sa.Column('best_figures', sa.String(length=10), nullable=False),
    sa.Column('five_wicket_hauls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('wicketkeepers',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('total_dismissals', sa.Integer(), nullable=False),
    sa.Column('catches', sa.Integer(), nullable=False),
    sa.Column('stumpings', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wicketkeepers')
    op.drop_table('bowlers')
    op.drop_table('batsmen')
    op.drop_table('allrounders')
    # ### end Alembic commands ###
